name: 'setting up runner environment'
description: 'make workflow to faster and efficient'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
#        node-version: 22.13.1
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json

    - name: install npm modules
      run: npm ci
      shell: bash

    - name: set nx cache action
      uses: actions/cache@v4
      id: nx-cache
      with:
        path: ${{ github.workspace }}/.nx
        key: nx-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          nx-cache-${{ runner.os }}-
    

