name: Release and Prod Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      latest_release_tag: ${{ steps.set-latest-release-tag.outputs.latest_release_tag }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: set latest release tag
        id: set-latest-release-tag
        run: |
          echo "latest_release_tag=$(git tag | grep -E '^v[0-9]+[.][0-9]+[.][0-9]+$' | sort -V | tail -n 1)" >> "$GITHUB_OUTPUT"


      - name: Generate a Git App installe token
        id: generate-token
        uses: actions/create-github-app-token@v1.12.0
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: "${{ github.repository_owner }}"
          #repositories: ${{ github.repository }}

      - name: release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: main
          token: ${{ steps.generate-token.outputs.token }}

      - name: release-please status
        run: echo "release_created=${{steps.release.outputs.release_created}}" >> "$GITHUB_OUTPUT"

  ci:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: for status check
        run: echo "always success for status check rule"
  auto-deploy:
    needs: release
    runs-on: ubuntu-latest
    env:
      LATEST_RELEASE_TAG: ${{ needs.release.outputs.latest_release_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set APP_ENV
        run: |
          echo "__APP_ENV=prod" >> "$GITHUB_ENV"

      - name: setup runtime
        uses: ./.github/actions/setup/
     
      # ターゲットはいつも本番
      - name: diff
        run: APP_ENV=$__APP_ENV npx nx affected --verbose --target diff --base=refs/tags/"${LATEST_RELEASE_TAG}" --head=remotes/origin/main     


      # ターゲットはいつも本番
      - name: deploy
        run: APP_ENV=$__APP_ENV npx nx affected --verbose --target deploy --base=refs/tags/"${LATEST_RELEASE_TAG}" --head=remotes/origin/main
        if: ${{ needs.release.outputs.release_created }}
     
